### ISSUE TITLE
Tests pass even with errors

### ISSUE THREAD

**Issue by vad101010** [NoraUi/NoraUi#138]
## Describe the bug

When I run the tests and intentionally put a scenario name that does not hesitate, the error is detected but the execution continues and ends as if there was no error.

## Expected Behavior

Maven test must fail after encontering the error

## Current Behavior

test continue

## Steps to Reproduce (for bugs)

just execute `clean test -PscenarioInitiator,prod,unit-tests,postIC,preIC "-Dcucumber.options=--tags '@lplayToLogoGame'" -e -ff -Dsurefire.skipAfterFailureCount=1`
and the result:

![image](https://user-images.githubusercontent.com/2040479/78582548-bac08380-7835-11ea-998b-c84c2ccba749.png)

## Context & Motivation

Working at Sopra Steria.
Trying to integrate the template into gitlab pipeline so it fails when an error is raised.

## Your Environment

* Robot generated by NoraUi Version: V4.2.1.0
* NoraUi Version used: V4.2.1
* Operating System and version: Unix and Windows
* Data input provider: Excel
* Data output provider: Excel
* Browser and version: Chrome 80
* WebDriver and version: ChromeDriver 80

**Comment by sgrillon14** [comment]
change `-Dcucumber.options=--tags '@lplayToLogoGame'"` by `-Dcucumber.options=--tags '@playToLogoGame'"`

**Comment by vad101010** [comment]
Maby I was a little bit confusing. Let me re-explain again:

I set the tag un purpose as wrong (ou can try with this if you want: `-Dcucumber.options=--tags '@ThisShouldCrash'"`.

But the problem is that when you run the maven test it is executing to the end and the result is that the build is OK. Where it is not OK because I have errors in the console and I know that my scenario don't exist. What I would like Nora to do when such thing happened is that the maven test fail and not succed.

**Comment by sgrillon14** [comment]
please see: https://noraui.github.io/#continuousIntegration

we **always** add this to Maven command: `-Dmaven.test.failure.ignore=true` otherwise the robot stops at the first error. The robot must never stop and **Maven must always return a "BUILD SUCCESS"**

Then you can choose to pass your job to KO if you find errors. you can also inject false values ​​in the "data input" to find deliberately KO executions. You then write the N ° of the step which must break in the column "result".
Example: https://github.com/NoraUi/NoraUi/blob/master/src/test/resources/data/in/hello.xlsx

the Maven "preIC" profile launches a counter (https://github.com/NoraUi/NoraUi/blob/master/src/main/java/com/github/noraui/indus/Counter.java) which allows to know the expected result. in your continuous integration you must have a script which compares the expected result and the obtained result.

here is an example of groovy script under Jenkins: https://noraui.github.io/#continuousIntegration

here is an example of shell script under Travic-CI: https://github.com/NoraUi/noraui-archetype/blob/master/test/run.sh

I hope I've helped you.

It is therefore not possible to knock out the build via NoraUI and Maven but it is a good idea to do it in the script (groovy, shell, ...).

We suggest that you search for the following sentence in your script and if you find it, you pass the job to KO:  "If you are using Excel as a dataProvider, you must choose one of the following formats: xls, xlsx, or xlsm."

in futur of NoraUI tag != scenario (https://github.com/NoraUi/NoraUi/issues/130), So I propose add a message in log if tag/scenario do not existe.

**Comment by vad101010** [comment]
Thank you for your time, I will proceed like this.
