### ISSUE TITLE
ClassCastException when ChromeDriver is used with a proxy

### ISSUE THREAD

**Issue by syalioune** [NoraUi/NoraUi#3]
This issue is related to [this](https://stackoverflow.com/questions/44853945/webdriverexception-when-i-use-a-proxy-with-chromedriver) stackoverflow issue.

When using ChromeDriver, Selenium tries to convert the Capabilities Object to JSON using BeanToJsonConverter#convertObject(Object, int) method. For trivial types, the conversion is done directly but for complex object, the method checks if the object has some specific methods in the following order :

- toMap or asMap
- toList or asList
- toJson

The org.openqa.selenium.Proxy has a toJson method which returns a Map whereas the BeanToJsonConverter#convertObject expect toJson method to return a String, hence the ClassCastException. 

...
Method toJson = getMethod(toConvert, "toJson");
    if (toJson != null) {
      try {
        Object res = toJson.invoke(toConvert);
        if (res instanceof JsonElement) {
          return (JsonElement) res;
        }
        try {
          return new JsonParser().parse(**(String) res**);
...

A temporary workaround while waiting for this issue to be fixed on Selenium side would be to :

- Create a NoraUIProxy class which inherits org.openqa.selenium.Proxy with a toMap method delegating to toJson
- Use NoraUIProxy in DriverFactory instead of Proxy

**Comment by ArKniiD** [comment]
Hello,

Since the chromewebdriver has been updated in 2.6.1 version, this problem does not seem to occur again.

Regarding the workaround, It won't be intergrated in the next version for the moment because proxies configuration will be reworked in it. This will allow users to set up several proxy of different types such as http or https.

So for the moment, I just can advise you to update your version of NoraUi to the 2.6.1.

Hoping that helps.

Regards
